### ISSUE TITLE
[feature request] Progress bar on "Aligning images on the grid" stage of tile loading

### ISSUE THREAD

**Issue by Pizzanomicon** [hanzhi713/image-collage-maker#25]
There is a notable lag in the process when loading tiles (Windows GUI) after "Aligning images on the grid...
Note: ### transparent tiles will be added to the grid"
Perhaps a progress bar would help in indicating if the process was frozen?  
Additionally, could CuPy/CUDA acceleration be used in this phase?

**Comment by hanzhi713** [comment]
Currently, this is done with a few lines of NumPy magic (see https://github.com/hanzhi713/image-collage-maker/blob/ea6c45753122135dc21cfd71b3b3edefe1a70fd2/make_img.py#L265). Because there's no loop, no progressbar is shown. 

Yes, a progress bar is possible. I just need to rewrite it with python code and not fully vectorized numpy code. Performance is quite similar, just a bit more code.

**Comment by hanzhi713** [comment]
Added in v5.2
